### ISSUE TITLE
CAD buttons don't work when TMI is loaded

### ISSUE THREAD

**Issue by cubinator** [Victorious3/Integrated-Circuits#182]
I created a new superflat map (with cheats allowed), placed and accessed a CAD and noticed that none of the buttons worked. Nothing happens when clicking on them. The following mods were loaded:
- CodeChickenCore-1.7.10-1.0.7.47
- CodeChickenLib-1.7.10-1.1.3.138
- ForgeMultipart-1.7.10-1.2.0.345
- ForgeRelocation-1.7.10-0.0.1.4
- ForgeRelocationFMP-1.7.10-0.0.1.2
- MrTJPCore-1.7.10
- buildcraft-7.1.8
- ComputerCraft1.74
- Industrial-Craft-2-Mod-Experimental-1.7.10
- IntegratedCircuits-1.7.10
- NBTEdit_1.7.10
- ProjectRed-1.7.10-Compat
- ProjectRed-1.7.10-Fabrication
- ProjectRed-1.7.10-Integration
- ProjectRed-1.7.10-Lighting
- ProjectRed-1.7.10-Mechanical
- ProjectRed-1.7.10-World
- ProjectRed-Base-1.7.10
- TooManyItems-1.7.10 (obviously)

When removing TMI from the mods-folder and launching Minecraft again, the CAD's buttons suddenly work. When TMI is loaded, the log additionally prints out the following:

```
[14:21:37] [main/INFO] [STDOUT]: [TMIForgeTransformer:transform:18]: [TMI] Rewriting class bex / net.minecraft.client.gui.inventory.GuiContainer
[14:21:39] [Client thread/ERROR] [FML]: Unable to determine registrant mod for TooManyItems. This is a critical error and should be impossible
java.lang.Throwable
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?]
    at TMIForgeContainer.<init>(TMIForgeContainer.java:35) [TMIForgeContainer.class:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_77]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_77]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_77]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_77]
    at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_77]
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:340) [Loader.class:?]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[14:42:34] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
```

I feel like I should report this to the TMI developers, but since this first happened when trying out IntegratedCircuits, I reported it here.

**Comment by ljfa-ag** [comment]
Well seems like TMI is doing some weird stuff. There is no source code available so we can't really figure out what it might be. I suggest you report it to the TMI developers.

**Comment by Victorious3** [comment]
I'd recommend switching to NEI, as I have specific support for it and its a more pleasant experience in general.

**Comment by ljfa-ag** [comment]
I didn't want to be that guy, but yeah I'd also say that ^^
