### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by wooky** [Victorious3/Integrated-Circuits#28]
```
java.lang.NullPointerException: Unexpected error
	at vic.mod.integratedcircuits.tile.BlockGate.func_149719_a(BlockGate.java:94)
	at vic.mod.integratedcircuits.tile.BlockGate.func_149668_a(BlockGate.java:101)
	at net.minecraft.tileentity.TileEntity.getRenderBoundingBox(TileEntity.java:365)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:481)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Absolutely no idea why this happened. Did not interact with this mod at all, with the exception of having an IC in my inventory.

**Comment by Victorious3** [comment]
Should be fixed with the newest build.

**Comment by wooky** [comment]
Hmm, that happened after I downloaded the r28 build. However, after reopening the game and playing for a few hours, I could not reproduce the bug.
