### ISSUE TITLE
Crash when ComputerCraft is not installed

### ISSUE THREAD

**Issue by wooky** [Victorious3/Integrated-Circuits#77]
````
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: vic/mod/integratedcircuits/gate/GatePeripheral
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: vic/mod/integratedcircuits/gate/GatePeripheral
	at vic.mod.integratedcircuits.IntegratedCircuits.preInit(IntegratedCircuits.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: vic.mod.integratedcircuits.gate.GatePeripheral
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheral
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.api.peripheral.IPeripheral
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
````
Works fine if CC is installed. I'm not sure if it's caused by having other mods installed, e.g. OpenComputers, MFR, etc., but not CC specifically. Let me know if more info is needed.

**Comment by Victorious3** [comment]
Same as #65 This is giving me a headache. The interfaces are bundled and there is no reason why they shouldn't load. I'll try to completely separate it for 0.9.

**Comment by sci4me** [comment]
What about @Optional.Interface from FML?

**Comment by Victorious3** [comment]
@sci4me It uses a codebase that's shared between OC and CC, it would take some time to make that possible. Has to be revisited for 0.9.

**Comment by sci4me** [comment]
@Victorious3 Not sure I understand... the classloader isn't loading your classes due to a lack of CC/OC interfaces right? Shouldn't @Optional fix that? Thought that was the whole point of @Optional...

**Comment by Victorious3** [comment]
The thing is, those classes *do exist*. They are bundled with my jar file.

**Comment by sci4me** [comment]
Huh...

What happens if they aren't bundled? I mean, @Optional should mean that they don't have to be bundled shouldn't it?

**Comment by Victorious3** [comment]
Extract of the license:
````
/**
 * This file is part of the public ComputerCraft API - http://www.computercraft.info
 * Copyright Daniel Ratcliffe, 2011-2014. This API may be redistributed unmodified and in full only.
 * For help using the API, and posting your mods, visit the forums at computercraft.info.
 */
```
And CC isn't open source, nor is there a deobf version I could use.

**Comment by sci4me** [comment]
And? I don't get it... move the apis into src/api and then use @Optional... should fix it?

**Comment by Victorious3** [comment]
I need those files because I use *the interfaces* for interacting with OC as well. But I said it already, I will rewrite some of it for 0.9.

**Comment by Victorious3** [comment]
Please comment on #65

**Comment by xBPMx** [comment]
Hello!

 

New message, please read <http://lowveld-tours.com/taking.php?4ed8>

 

feend@ntlworld.com

**Comment by xBPMx** [comment]
Hello!

 

New message, please read <http://visa24.info/none.php?5ltu>

 

feend@ntlworld.com
